### ISSUE TITLE
你的TextureManager会内存泄漏啊

### ISSUE THREAD

**Issue by xanahopper** [hellokenlee/NeneEngine#1]
你FreeImage_LoadImage和FreeImage_ConvertTo32Bits之后，都没有将对应的FIBITMAP使用FreeImage_Unload释放掉啊！

**Comment by hellokenlee** [comment]
是的，我在写的时候就注意到了。 因为之前是一个方法，后来分开变成了loadImage()和loadTexture()两个方法之后就没改正过来，已经在头文件标注了， 之后会改正过来的。 谢谢你的细心~ ( 么么哒 XD

**Comment by xanahopper** [comment]
另外……我问一下……你的Cubemap映射出来是正常的么？我按照标准方法映射出来前后左右的上下是颠倒的……

**Comment by hellokenlee** [comment]
这是因为你读图片的库和OpenGL的纹理处理坐标不一样， 数字图像认为原点在左上角， OpenGL认为在左下角。你可以翻转一下uv或者纹理就好。你可以看到TextureManager里面有
```
FreeImage_FlipVertical(imagePtr);
```

**Comment by xanahopper** [comment]
……我说呢……我还在shader里做了翻转……郁闷……谢了
