### ISSUE TITLE
楼主对unity/unreal之类的引擎是否有了解？

### ISSUE THREAD

**Issue by prife** [hellokenlee/NeneEngine#2]
请教下楼主对Unity/Unreal的引擎是否有了解？
以楼主对游戏引擎的理解，游戏内的自动化测试，举个例子，王者荣耀等类似的双摇杆游戏，方便的编写测试用例实现自动跑图覆盖场景，这种想法是否可行？

PS. 俺从事游戏行业（正经单位），最近在看LearnOpenGL中文版，看到PBR那章，原来是楼主翻译的，就找过来了，实在冒昧

**Comment by hellokenlee** [comment]
issue 回复不及时... 这种问题最好邮件问。
